CREATE TABLE 0_ks_import_documents (
  id bigint unsigned NOT NULL AUTO_INCREMENT,
  trans_type smallint NOT NULL,
  trans_no int unsigned NOT NULL,
  supplier_id int unsigned NOT NULL,
  dud_no varchar(80) NOT NULL,
  dud_date date NOT NULL,
  clearance_date date NOT NULL,
  customs_office varchar(120) NOT NULL DEFAULT '',
  origin_country varchar(80) NOT NULL,
  incoterm varchar(20) NOT NULL DEFAULT '',
  customs_exchange_rate decimal(18,8) NOT NULL DEFAULT 1,
  tariff_codes text,
  customs_value decimal(18,2) NOT NULL DEFAULT 0,
  customs_duty decimal(18,2) NOT NULL DEFAULT 0,
  excise decimal(18,2) NOT NULL DEFAULT 0,
  import_vat_base decimal(18,2) NOT NULL DEFAULT 0,
  import_vat decimal(18,2) NOT NULL DEFAULT 0,
  eur1_reference varchar(80) NOT NULL DEFAULT '',
  import_notes text,
  created_by varchar(60) NOT NULL DEFAULT '',
  created_at datetime NOT NULL,
  updated_by varchar(60) NOT NULL DEFAULT '',
  updated_at datetime NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY trans_link (trans_type, trans_no),
  KEY dud_no (dud_no),
  KEY supplier_id (supplier_id),
  KEY dud_date (dud_date),
  KEY clearance_date (clearance_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
