CREATE TABLE 0_ks_import_payment_splits (
  id bigint unsigned NOT NULL AUTO_INCREMENT,
  import_trans_type smallint NOT NULL,
  import_trans_no int unsigned NOT NULL,
  goods_supplier_id int unsigned NOT NULL,
  goods_amount decimal(18,2) NOT NULL DEFAULT 0,
  goods_currency varchar(3) NOT NULL DEFAULT '',
  forwarder_id int unsigned NOT NULL DEFAULT 0,
  customs_duty decimal(18,2) NOT NULL DEFAULT 0,
  excise decimal(18,2) NOT NULL DEFAULT 0,
  import_vat decimal(18,2) NOT NULL DEFAULT 0,
  customs_other decimal(18,2) NOT NULL DEFAULT 0,
  forwarder_amount decimal(18,2) NOT NULL DEFAULT 0,
  transport_supplier_id int unsigned NOT NULL DEFAULT 0,
  transport_amount decimal(18,2) NOT NULL DEFAULT 0,
  company_currency varchar(3) NOT NULL DEFAULT '',
  status varchar(20) NOT NULL DEFAULT 'draft',
  goods_credit_type smallint NOT NULL DEFAULT 0,
  goods_credit_no int unsigned NOT NULL DEFAULT 0,
  forwarder_invoice_type smallint NOT NULL DEFAULT 0,
  forwarder_invoice_no int unsigned NOT NULL DEFAULT 0,
  transport_invoice_type smallint NOT NULL DEFAULT 0,
  transport_invoice_no int unsigned NOT NULL DEFAULT 0,
  confirmed_by varchar(60) NOT NULL DEFAULT '',
  confirmed_at datetime NULL,
  cancelled_by varchar(60) NOT NULL DEFAULT '',
  cancelled_at datetime NULL,
  created_by varchar(60) NOT NULL DEFAULT '',
  created_at datetime NOT NULL,
  updated_by varchar(60) NOT NULL DEFAULT '',
  updated_at datetime NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY import_link (import_trans_type, import_trans_no),
  KEY goods_supplier_id (goods_supplier_id),
  KEY forwarder_id (forwarder_id),
  KEY transport_supplier_id (transport_supplier_id),
  KEY status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
