CREATE TABLE 0_ks_purchase_imports (
 id bigint unsigned NOT NULL AUTO_INCREMENT,
 reference varchar(40) NOT NULL,
 status varchar(12) NOT NULL DEFAULT 'draft',
 supplier_id int unsigned NOT NULL,
 supplier_invoice_no varchar(60) NOT NULL,
 invoice_date date NOT NULL,
 due_date date NOT NULL,
 currency varchar(3) NOT NULL,
 exchange_rate decimal(18,8) NOT NULL DEFAULT 1,
 location_code varchar(5) NOT NULL,
 origin_country varchar(80) NOT NULL DEFAULT '',
 dispatch_country varchar(80) NOT NULL DEFAULT '',
 dud_no varchar(80) NOT NULL DEFAULT '',
 dud_date date DEFAULT NULL,
 declaration_type varchar(20) NOT NULL DEFAULT '',
 customs_office varchar(120) NOT NULL DEFAULT '',
 incoterm varchar(20) NOT NULL DEFAULT '',
 transport_mode varchar(12) NOT NULL DEFAULT 'included',
 transport_supplier_id int unsigned NOT NULL DEFAULT 0,
 transport_trans_no int unsigned NOT NULL DEFAULT 0,
 transport_invoice_no varchar(60) NOT NULL DEFAULT '',
 freight_base decimal(18,2) NOT NULL DEFAULT 0,
 insurance_base decimal(18,2) NOT NULL DEFAULT 0,
 handling_base decimal(18,2) NOT NULL DEFAULT 0,
 terminal_base decimal(18,2) NOT NULL DEFAULT 0,
 forwarding_base decimal(18,2) NOT NULL DEFAULT 0,
 other_base decimal(18,2) NOT NULL DEFAULT 0,
 allocation_method varchar(12) NOT NULL DEFAULT 'value',
 goods_currency decimal(18,2) NOT NULL DEFAULT 0,
 goods_base decimal(18,2) NOT NULL DEFAULT 0,
 customs_value_base decimal(18,2) NOT NULL DEFAULT 0,
 duty_base decimal(18,2) NOT NULL DEFAULT 0,
 excise_base decimal(18,2) NOT NULL DEFAULT 0,
 vat_base decimal(18,2) NOT NULL DEFAULT 0,
 vat_amount decimal(18,2) NOT NULL DEFAULT 0,
 landed_total decimal(18,2) NOT NULL DEFAULT 0,
 supplier_trans_no int unsigned NOT NULL DEFAULT 0,
 supplier_invoice_created tinyint(1) NOT NULL DEFAULT 0,
 po_no int unsigned NOT NULL DEFAULT 0,
 grn_no int unsigned NOT NULL DEFAULT 0,
 journal_no int unsigned NOT NULL DEFAULT 0,
 notes text,
 created_by varchar(60) NOT NULL DEFAULT '',
 created_at datetime NOT NULL,
 updated_by varchar(60) NOT NULL DEFAULT '',
 updated_at datetime NOT NULL,
 posted_by varchar(60) NOT NULL DEFAULT '',
 posted_at datetime DEFAULT NULL,
 voided_by varchar(60) NOT NULL DEFAULT '',
 voided_at datetime DEFAULT NULL,
 void_reason varchar(255) NOT NULL DEFAULT '',
 PRIMARY KEY(id), UNIQUE KEY reference(reference), UNIQUE KEY dud_no(dud_no),
 KEY supplier_id(supplier_id), KEY status(status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE 0_ks_purchase_import_lines (
 id bigint unsigned NOT NULL AUTO_INCREMENT,
 import_id bigint unsigned NOT NULL,
 stock_id varchar(20) NOT NULL,
 description varchar(255) NOT NULL,
 quantity decimal(18,4) NOT NULL,
 uom varchar(20) NOT NULL DEFAULT '',
 unit_price_currency decimal(18,6) NOT NULL,
 line_currency decimal(18,2) NOT NULL,
 line_base decimal(18,2) NOT NULL,
 tariff_code varchar(24) NOT NULL DEFAULT '',
 origin_country varchar(80) NOT NULL DEFAULT '',
 net_weight decimal(18,4) NOT NULL DEFAULT 0,
 gross_weight decimal(18,4) NOT NULL DEFAULT 0,
 duty_rate decimal(8,4) NOT NULL DEFAULT 0,
 duty_override decimal(18,2) NOT NULL DEFAULT 0,
 duty_amount decimal(18,2) NOT NULL DEFAULT 0,
 excise_amount decimal(18,2) NOT NULL DEFAULT 0,
 vat_rate decimal(8,4) NOT NULL DEFAULT 18,
 vat_base_override decimal(18,2) NOT NULL DEFAULT 0,
 vat_amount_override decimal(18,2) NOT NULL DEFAULT 0,
 customs_value decimal(18,2) NOT NULL DEFAULT 0,
 vat_base decimal(18,2) NOT NULL DEFAULT 0,
 vat_amount decimal(18,2) NOT NULL DEFAULT 0,
 import_cost_allocated decimal(18,2) NOT NULL DEFAULT 0,
 landed_cost decimal(18,2) NOT NULL DEFAULT 0,
 unit_landed_cost decimal(18,6) NOT NULL DEFAULT 0,
 PRIMARY KEY(id), KEY import_id(import_id), KEY stock_id(stock_id),
 CONSTRAINT 0_ks_purchase_import_lines_fk FOREIGN KEY(import_id)
  REFERENCES 0_ks_purchase_imports(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE 0_ks_purchase_import_settings (
 setting_key varchar(60) NOT NULL, setting_value varchar(255) NOT NULL DEFAULT '',
 PRIMARY KEY(setting_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT IGNORE INTO 0_ks_purchase_import_settings(setting_key, setting_value) VALUES
('default_location',''),('customs_payable_account',''),('landed_cost_clearing_account',''),
('vat_tax_type_18','0'),('vat_tax_type_8','0');
