CREATE TABLE 0_ks_imports (
    id bigint unsigned NOT NULL AUTO_INCREMENT,
    reference varchar(40) NOT NULL,
    status varchar(12) NOT NULL DEFAULT 'draft',
    supplier_id int unsigned NOT NULL DEFAULT 0,
    supplier_invoice_no varchar(60) NOT NULL DEFAULT '',
    supplier_invoice_date date DEFAULT NULL,
    supplier_trans_no int unsigned NOT NULL DEFAULT 0,
    origin_country varchar(80) NOT NULL DEFAULT '',
    dispatch_country varchar(80) NOT NULL DEFAULT '',
    dud_no varchar(80) NOT NULL DEFAULT '',
    dud_date date DEFAULT NULL,
    customs_office varchar(120) NOT NULL DEFAULT '',
    incoterm varchar(20) NOT NULL DEFAULT '',
    currency varchar(3) NOT NULL DEFAULT 'EUR',
    exchange_rate decimal(18,8) NOT NULL DEFAULT 1.00000000,
    goods_amount_currency decimal(18,2) NOT NULL DEFAULT 0.00,
    goods_amount_base decimal(18,2) NOT NULL DEFAULT 0.00,
    transport_mode varchar(12) NOT NULL DEFAULT 'included',
    transport_invoice_no varchar(60) NOT NULL DEFAULT '',
    transport_supplier_id int unsigned NOT NULL DEFAULT 0,
    transport_trans_no int unsigned NOT NULL DEFAULT 0,
    transport_amount_base decimal(18,2) NOT NULL DEFAULT 0.00,
    insurance_amount_base decimal(18,2) NOT NULL DEFAULT 0.00,
    handling_amount_base decimal(18,2) NOT NULL DEFAULT 0.00,
    customs_value_override decimal(18,2) NOT NULL DEFAULT 0.00,
    customs_value_base decimal(18,2) NOT NULL DEFAULT 0.00,
    customs_duty_base decimal(18,2) NOT NULL DEFAULT 0.00,
    excise_base decimal(18,2) NOT NULL DEFAULT 0.00,
    terminal_amount_base decimal(18,2) NOT NULL DEFAULT 0.00,
    forwarding_amount_base decimal(18,2) NOT NULL DEFAULT 0.00,
    other_amount_base decimal(18,2) NOT NULL DEFAULT 0.00,
    import_vat_rate decimal(8,4) NOT NULL DEFAULT 18.0000,
    import_vat_base_override decimal(18,2) NOT NULL DEFAULT 0.00,
    import_vat_amount_override decimal(18,2) NOT NULL DEFAULT 0.00,
    import_vat_base decimal(18,2) NOT NULL DEFAULT 0.00,
    import_vat_amount decimal(18,2) NOT NULL DEFAULT 0.00,
    allocation_method varchar(12) NOT NULL DEFAULT 'value',
    notes text,
    created_by varchar(60) NOT NULL DEFAULT '',
    created_at datetime NOT NULL,
    updated_by varchar(60) NOT NULL DEFAULT '',
    updated_at datetime NOT NULL,
    posted_by varchar(60) NOT NULL DEFAULT '',
    posted_at datetime DEFAULT NULL,
    gl_trans_no int unsigned NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY reference (reference),
    KEY dud_no (dud_no),
    KEY supplier_id (supplier_id),
    KEY status (status),
    KEY supplier_trans (supplier_trans_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE 0_ks_import_items (
    id bigint unsigned NOT NULL AUTO_INCREMENT,
    import_id bigint unsigned NOT NULL,
    stock_id varchar(20) NOT NULL DEFAULT '',
    description varchar(255) NOT NULL DEFAULT '',
    quantity decimal(18,4) NOT NULL DEFAULT 0.0000,
    weight decimal(18,4) NOT NULL DEFAULT 0.0000,
    invoice_value_base decimal(18,2) NOT NULL DEFAULT 0.00,
    manual_share decimal(12,8) NOT NULL DEFAULT 0.00000000,
    duty_allocated decimal(18,2) NOT NULL DEFAULT 0.00,
    excise_allocated decimal(18,2) NOT NULL DEFAULT 0.00,
    transport_allocated decimal(18,2) NOT NULL DEFAULT 0.00,
    insurance_allocated decimal(18,2) NOT NULL DEFAULT 0.00,
    handling_allocated decimal(18,2) NOT NULL DEFAULT 0.00,
    terminal_allocated decimal(18,2) NOT NULL DEFAULT 0.00,
    forwarding_allocated decimal(18,2) NOT NULL DEFAULT 0.00,
    other_allocated decimal(18,2) NOT NULL DEFAULT 0.00,
    landed_cost decimal(18,2) NOT NULL DEFAULT 0.00,
    unit_landed_cost decimal(18,6) NOT NULL DEFAULT 0.000000,
    PRIMARY KEY (id),
    KEY import_id (import_id),
    KEY stock_id (stock_id),
    CONSTRAINT 0_ks_import_items_fk FOREIGN KEY (import_id)
        REFERENCES 0_ks_imports (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE 0_ks_import_links (
    id bigint unsigned NOT NULL AUTO_INCREMENT,
    import_id bigint unsigned NOT NULL,
    role varchar(24) NOT NULL,
    trans_type smallint NOT NULL DEFAULT 0,
    trans_no int unsigned NOT NULL DEFAULT 0,
    supplier_id int unsigned NOT NULL DEFAULT 0,
    invoice_ref varchar(60) NOT NULL DEFAULT '',
    amount_base decimal(18,2) NOT NULL DEFAULT 0.00,
    tax_amount decimal(18,2) NOT NULL DEFAULT 0.00,
    included_in_customs tinyint(1) NOT NULL DEFAULT 0,
    created_at datetime NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY import_role_trans (import_id, role, trans_type, trans_no),
    KEY import_id (import_id),
    CONSTRAINT 0_ks_import_links_fk FOREIGN KEY (import_id)
        REFERENCES 0_ks_imports (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE 0_ks_import_settings (
    setting_key varchar(60) NOT NULL,
    setting_value varchar(255) NOT NULL DEFAULT '',
    PRIMARY KEY (setting_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT IGNORE INTO 0_ks_import_settings (setting_key, setting_value) VALUES
('default_vat_rate', '18'),
('inventory_account', '1510'),
('freight_account', '5100'),
('input_vat_account', '2150'),
('customs_payable_account', '2100'),
('landed_cost_clearing_account', '1550');
