<?php
$page_security='SA_KS_IMPORT_ENTRY'; $path_to_root='../..';
include_once($path_to_root.'/includes/session.inc'); add_access_extensions();
include_once($path_to_root.'/includes/ui.inc'); include_once($path_to_root.'/includes/date_functions.inc');
include_once($path_to_root.'/inventory/includes/db/items_db.inc');
include_once($path_to_root.'/modules/ks_imports/includes/purchase_import_db.inc');
include_once($path_to_root.'/modules/ks_imports/includes/purchase_import_calc.inc');
include_once($path_to_root.'/modules/ks_imports/includes/purchase_import_posting.inc');
page(_($help_context='Blerje nga importi'),false,false,'',user_use_date_picker()?get_js_date_picker():'');
$id=(int)get_post('import_id',isset($_GET['id'])?$_GET['id']:0);
function kspi_post_header(){return array(
 'reference'=>trim(get_post('reference')),'supplier_id'=>(int)get_post('supplier_id'),
 'supplier_invoice_no'=>trim(get_post('supplier_invoice_no')),'invoice_date'=>get_post('invoice_date'),
 'due_date'=>get_post('due_date'),'currency'=>get_post('currency','EUR'),'exchange_rate'=>kspi_num(get_post('exchange_rate',1)),
 'location_code'=>get_post('location_code'),'origin_country'=>trim(get_post('origin_country')),
 'dispatch_country'=>trim(get_post('dispatch_country')),'dud_no'=>trim(get_post('dud_no')),'dud_date'=>get_post('dud_date'),
 'declaration_type'=>trim(get_post('declaration_type')),'customs_office'=>trim(get_post('customs_office')),
 'incoterm'=>trim(get_post('incoterm')),'transport_mode'=>get_post('transport_mode','included'),
 'transport_supplier_id'=>(int)get_post('transport_supplier_id'),'transport_trans_no'=>(int)get_post('transport_trans_no'),
 'transport_invoice_no'=>trim(get_post('transport_invoice_no')),'freight_base'=>kspi_num(get_post('freight_base')),
 'insurance_base'=>kspi_num(get_post('insurance_base')),'handling_base'=>kspi_num(get_post('handling_base')),
 'terminal_base'=>kspi_num(get_post('terminal_base')),'forwarding_base'=>kspi_num(get_post('forwarding_base')),
 'other_base'=>kspi_num(get_post('other_base')),'allocation_method'=>get_post('allocation_method','value'),
 'notes'=>trim(get_post('notes')));}
function kspi_header_ok($d){$ok=true;foreach(array('reference','supplier_id','supplier_invoice_no','invoice_date','currency','location_code') as $f)if(empty($d[$f])){display_error(sprintf(_('Fusha %s eshte e detyrueshme.'),$f));$ok=false;}if($d['exchange_rate']<=0){display_error(_('Kursi duhet te jete mbi zero.'));$ok=false;}return $ok;}
function kspi_recalc_save($id){$h=kspi_get($id);list($lines,$totals)=kspi_recalculate($h,kspi_lines($id));kspi_store_calculation($id,$lines,$totals);}
if(isset($_POST['save_header'])){$d=kspi_post_header();if(kspi_header_ok($d)){begin_transaction();$id=kspi_save_header($id,$d);kspi_recalc_save($id);commit_transaction();display_notification(_('Dokumenti Draft u ruajt. Tani regjistroni artikujt.'));}}
if(isset($_POST['add_line'])&&$id){$d=array('stock_id'=>get_post('new_stock_id'),'description'=>trim(get_post('new_description')),
 'quantity'=>kspi_num(get_post('new_quantity')),'unit_price_currency'=>kspi_num(get_post('new_unit_price')),
 'tariff_code'=>trim(get_post('new_tariff_code')),'origin_country'=>trim(get_post('new_origin_country')),
 'net_weight'=>kspi_num(get_post('new_net_weight')),'gross_weight'=>kspi_num(get_post('new_gross_weight')),
 'duty_rate'=>kspi_num(get_post('new_duty_rate')),'duty_override'=>kspi_num(get_post('new_duty_override')),
 'excise_amount'=>kspi_num(get_post('new_excise')),'vat_rate'=>kspi_num(get_post('new_vat_rate',18)),
 'vat_base_override'=>kspi_num(get_post('new_vat_base')),'vat_amount_override'=>kspi_num(get_post('new_vat_amount')));
 $h=kspi_get($id);$item=get_item($d['stock_id']);if(!$h||$h['status']!='draft')display_error(_('Vetem Drafti mund te ndryshohet.'));elseif(!$item||$item['mb_flag']!='B'||$d['quantity']<=0||$d['unit_price_currency']<0)display_error(_('Zgjidhni artikull inventari dhe shkruani sasine e cmimin.'));elseif(!$d['tariff_code'])display_error(_('Kodi tarifor eshte i detyrueshem.'));else{begin_transaction();kspi_add_line($id,$d);kspi_recalc_save($id);commit_transaction();display_notification(_('Artikulli u shtua.'));}}
$del=find_submit('DeleteLine',false);if($del!==null&&$id){begin_transaction();kspi_delete_line($id,$del);kspi_recalc_save($id);commit_transaction();}
if(isset($_POST['mark_ready'])&&$id){$h=kspi_get($id);$lines=kspi_lines($id);if(!count($lines))display_error(_('Regjistroni te pakten nje artikull.'));elseif(!$h['dud_no']||!$h['dud_date'])display_error(_('DUD-i dhe data jane te detyrueshme.'));else{kspi_mark_ready($id);display_notification(_('Dokumenti u kontrollua. Ende nuk eshte postuar.'));}}
if(isset($_POST['reopen'])&&$id){kspi_reopen($id);display_notification(_('Dokumenti u rikthye ne Draft.'));}
if(isset($_POST['post_import'])&&$id){list($ok,$errors)=kspi_post($id);if($ok)display_notification(_('Blerja nga importi u postua ne furnitor, stok, GL dhe regjistrin tatimor.'));else foreach($errors as $e)display_error($e);}
$h=$id?kspi_get($id):false;if(!$h)$h=array('reference'=>kspi_next_ref(),'status'=>'draft','supplier_id'=>0,'supplier_invoice_no'=>'','invoice_date'=>date2sql(Today()),'due_date'=>date2sql(Today()),'currency'=>'EUR','exchange_rate'=>1,'location_code'=>kspi_setting('default_location'),'origin_country'=>'','dispatch_country'=>'','dud_no'=>'','dud_date'=>date2sql(Today()),'declaration_type'=>'IM4','customs_office'=>'','incoterm'=>'','transport_mode'=>'included','transport_supplier_id'=>0,'transport_trans_no'=>0,'transport_invoice_no'=>'','freight_base'=>0,'insurance_base'=>0,'handling_base'=>0,'terminal_base'=>0,'forwarding_base'=>0,'other_base'=>0,'allocation_method'=>'value','notes'=>'','goods_currency'=>0,'goods_base'=>0,'customs_value_base'=>0,'duty_base'=>0,'excise_base'=>0,'vat_base'=>0,'vat_amount'=>0,'landed_total'=>0);
if(!isset($_POST['reference']))foreach($h as $k=>$v)$_POST[$k]=in_array($k,array('invoice_date','due_date','dud_date'))&&$v?sql2date($v):$v;
display_heading(_('BLERJE NGA IMPORTI'));
display_note(_('Rrjedha native: Supplier Invoice + Purchase Order + GRN + Stock + GL + TVSH/DUD + Landed Cost.'),0,1);
start_form();hidden('import_id',$id);start_outer_table(TABLESTYLE2);table_section(1);table_section_title(_('Furnitori dhe dokumenti'));
text_row(_('Referenca e importit:'),'reference',null,24,40);supplier_list_row(_('Furnitori i huaj:'),'supplier_id',null,_('Zgjidhni furnitorin'),true);
text_row(_('Nr. fatures se furnitorit:'),'supplier_invoice_no',null,28,60);date_row(_('Data e fatures:'),'invoice_date');date_row(_('Afati i pageses:'),'due_date');currencies_list_row(_('Monedha:'),'currency');amount_row(_('Kursi ne EUR:'),'exchange_rate',null,null,null,6);locations_list_row(_('Prano ne depo:'),'location_code');
table_section_title(_('DUD dhe origjina'));text_row(_('Numri DUD:'),'dud_no',null,28,80);date_row(_('Data DUD:'),'dud_date');text_row(_('Lloji i deklarates:'),'declaration_type',null,12,20);text_row(_('Zyra doganore:'),'customs_office',null,28,120);text_row(_('Shteti i origjines:'),'origin_country',null,24,80);text_row(_('Shteti i dergimit:'),'dispatch_country',null,24,80);text_row(_('Incoterm:'),'incoterm',null,12,20);
table_section(2);table_section_title(_('Transporti dhe faturat percjellese'));array_selector_row(_('Transporti:'),'transport_mode',null,array('included'=>_('Ne faturen e huaj'),'separate'=>_('Fature e vecante'),'none'=>_('Pa transport')));supplier_list_row(_('Transportuesi:'),'transport_supplier_id',null,_('Zgjidhni'),true);array_selector_row(_('Fatura e transportit ne Blerje:'),'transport_trans_no',null,kspi_transport_invoices((int)get_post('transport_supplier_id')));text_row(_('Nr. fatures transportit:'),'transport_invoice_no',null,24,60);amount_row(_('Transport EUR:'),'freight_base');amount_row(_('Sigurim EUR:'),'insurance_base');amount_row(_('Manipulim EUR:'),'handling_base');amount_row(_('Terminal EUR:'),'terminal_base');amount_row(_('Shpedicion EUR:'),'forwarding_base');amount_row(_('Kosto tjera EUR:'),'other_base');array_selector_row(_('Shperndarja e kostos:'),'allocation_method',null,array('value'=>_('Sipas vleres'),'quantity'=>_('Sipas sasise'),'weight'=>_('Sipas peshes')));textarea_row(_('Shenime:'),'notes',null,34,4,1000);end_outer_table(1);
if($h['status']=='draft')submit_center('save_header',_($id?'Ruaj ndryshimet':'Krijo Draftin'),true,'','default');end_form();
if($id){$h=kspi_get($id);$lines=kspi_lines($id);display_heading(_('Artikujt e fatures dhe te DUD-it'));start_form();hidden('import_id',$id);start_table(TABLESTYLE,"width='99%'");table_header(array(_('Kodi / Emertimi'),_('Sasia / Cmimi'),_('Tarifa / Origjina'),_('Pesha neto/bruto'),_('Dogana / Akciza'),_('TVSH'),_('Vlera EUR'),_('Landed cost'),''));$k=0;foreach($lines as $l){alt_table_row_color($k);label_cell('<b>'.$l['stock_id'].'</b><br>'.$l['description']);label_cell(qty_format($l['quantity']).' '.$l['uom'].'<br>'.price_format($l['unit_price_currency']).' '.$h['currency']);label_cell($l['tariff_code'].'<br>'.$l['origin_country']);label_cell(qty_format($l['net_weight']).' / '.qty_format($l['gross_weight']));label_cell(percent_format($l['duty_rate']).'% = '.price_format($l['duty_amount']).'<br>'._('Akciza').': '.price_format($l['excise_amount']));label_cell(percent_format($l['vat_rate']).'%<br>'.price_format($l['vat_amount']));amount_cell($l['line_base']);amount_cell($l['landed_cost']);if($h['status']=='draft')delete_button_cell('DeleteLine'.$l['id'],_('Fshi'));else label_cell('');end_row();}
if($h['status']=='draft'){start_row();stock_items_list_cells(null,'new_stock_id',null,false);text_cells(null,'new_description',null,22,255);label_cell(_('Plotesoni rreshtin poshte'));label_cell('');label_cell('');label_cell('');label_cell('');label_cell('');label_cell('');end_row();}end_table(1);
if($h['status']=='draft'){start_table(TABLESTYLE2);table_section_title(_('Shto artikull'));qty_row(_('Sasia:'),'new_quantity');amount_row(_('Cmimi per njesi ne monedhen e fatures:'),'new_unit_price');text_row(_('Kodi tarifor:'),'new_tariff_code',null,20,24);text_row(_('Origjina e artikullit:'),'new_origin_country',get_post('origin_country'),24,80);qty_row(_('Pesha neto:'),'new_net_weight');qty_row(_('Pesha bruto:'),'new_gross_weight');amount_row(_('Norma doganore:'),'new_duty_rate',null,null,'%');amount_row(_('Dogana sipas DUD (opsionale):'),'new_duty_override');amount_row(_('Akciza:'),'new_excise');amount_row(_('Norma TVSH:'),'new_vat_rate',18,null,'%');amount_row(_('Baza TVSH sipas DUD (opsionale):'),'new_vat_base');amount_row(_('TVSH sipas DUD (opsionale):'),'new_vat_amount');end_table(1);submit_center('add_line',_('Shto artikullin'),true,'','default');}
display_heading(_('Totali i importit'));start_table(TABLESTYLE2);label_row(_('Mall ne monedhen e fatures:'),price_format($h['goods_currency']).' '.$h['currency']);label_row(_('Mall ne EUR:'),price_format($h['goods_base']));label_row(_('Vlera doganore:'),price_format($h['customs_value_base']));label_row(_('Dogana + akciza:'),price_format($h['duty_base']+$h['excise_base']));label_row(_('TVSH ne import:'),price_format($h['vat_amount']));label_row(_('Landed cost pa TVSH te zbritshme:'),price_format($h['landed_total']));end_table(1);
if($h['status']=='draft')submit_center('mark_ready',_('Kontrollo dokumentin'),true,_('Nuk poston ende.'),'default');elseif($h['status']=='ready'){start_table(TABLESTYLE_NOBORDER);start_row();submit_cells('reopen',_('Rikthe ne Draft'),'','',true);submit_cells('post_import',_('Posto blerjen nga importi'),'','',true);end_row();end_table();submit_js_confirm('post_import',_('Do te krijohen fatura, PO/GRN, stoku dhe GL. Vazhdoni?'));}elseif($h['status']=='posted'){display_note(sprintf(_('Postuar: Supplier Invoice #%d | PO #%d | GRN #%d | Journal #%d'),$h['supplier_trans_no'],$h['po_no'],$h['grn_no'],$h['journal_no']),0,1);}end_form();}
end_page();
